USE AUTOPRO

--DROP TABLE USER
CREATE TABLE PRO_USER
(
	ID	INT IDENTITY(1,1) CONSTRAINT pkUserId PRIMARY KEY,
	LOGIN NVARCHAR(50) CONSTRAINT uUserLogin UNIQUE NOT NULL,
	PASSWORD NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,	
	TEL	NVARCHAR(50)
)

CREATE TABLE PRO_ROLE
(
	ID	INT	IDENTITY(1,1) CONSTRAINT pkRoleId PRIMARY KEY,
	NAME	NVARCHAR(50) NOT NULL
)

CREATE TABLE PRO_USERROLE
(
	ID	INT IDENTITY(1,1) CONSTRAINT pkUseroleId PRIMARY KEY,
	ID_USER INT REFERENCES PRO_USER(ID) NOT NULL,
	ID_ROLE INT REFERENCES PRO_ROLE(ID) NOT NULL
)

GO